import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import './globals.css'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={"main-content"}>
          <div className="wrapper wrapper--inner">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
